### ISSUE TITLE
Could not log in: received unexpected status code 401

### ISSUE THREAD

**Issue by stlsw** [virtualzone/onedrive-uploader#18]
Hi @virtualzone ,
Thanks for developing this great tool. I kept getting the 401 errors even though everything is configured correctly. you can refer to the screen recording, thank you again !
https://user-images.githubusercontent.com/9862466/198870703-c35fb9b5-1447-43ba-ab74-bc3853335d53.mp4

**Comment by virtualzone** [comment]
Hi @stlsw , 
this usually happens when copying the Secret ID instead of the Secret Value. Please ensure you've used the Secret Value.

<img width="1028" alt="Screenshot 2022-11-06 at 20 35 10" src="https://user-images.githubusercontent.com/13085858/200191261-a7109124-8f90-4137-a4b1-711df47499f6.png">

**Comment by virtualzone** [comment]
I guess my hint fixed the issue. If it didn't, please reopen this ticket.
